### ISSUE TITLE
Make a Civic Issue Twitter Bot

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/civic-issue-finder#16]
Post a random "help wanted" civic tech issue to Twitter thrice a day.

A general bot would use this url 
`http://codeforamerica.org/api/issues/labels/help wanted?per_page=1`

Make it specific for your Brigade
`http://codeforamerica.org/api/issues/labels/help wanted?organization_name=Code for San Francisco&per_page=1`

Make one for Code for All or Brigade wide
`http://codeforamerica.org/api/issues/labels/help wanted?organization_type=Code for All&per_page=1`

Cross posted at https://github.com/codeforamerica/health-project-ideas/issues/42

**Comment by urbildpunkt** [comment]
I just wanted to point it out here too that I setup a twitter bot that posts open civic issues a few times a day [@civicissues](https://twitter.com/civicissues).
