### ISSUE TITLE
Use schema-relative links for stylesheets, etc.

### ISSUE THREAD

**Issue by migurski** [codeforamerica/civic-issue-finder#25]
Switch from `http://…` to `//…` in links and hrefs to correctly pick up SSL things.

See also https://github.com/codeforamerica/codeforamerica.org/issues/529#issuecomment-72910733.

**Comment by ondrae** [comment]
Done in https://github.com/codeforamerica/civic-issue-finder/commit/6d6433654a99250cefeb57598f53bf26f11bc1bd
