### ISSUE TITLE
Increase the variety of issues shown

### ISSUE THREAD

**Issue by cjerdonek** [codeforamerica/civic-issue-finder#29]
It would be better if the widget somehow increased the variety of issues shown (e.g. by selecting at random from all open issues).  Currently, on the Code for SF home page for example, the same issues from the same project are always shown, even though there are probably a dozen different projects with open issues to work on.

**Comment by ondrae** [comment]
Hey @cjerdonek this is for sure a bug. We were intending for them to be returned randomly. I think api call to a specific Brigade are showing up in order. Can you check this out @tmaybe ?

**Comment by ondrae** [comment]
Done!

**Comment by cjerdonek** [comment]
Awesome, thanks! :grinning:
