### ISSUE TITLE
Project link is broken

### ISSUE THREAD

**Issue by donmccurdy** [codeforamerica/civic-issue-finder#49]
I'm getting a 404 at https://www.codeforamerica.org/geeks/civicissues

**Comment by fureigh** [comment]
+1. It sounds like it's caught up in a [larger routing issue](https://github.com/codeforamerica/cfapi/issues/306#issuecomment-246908309). @ondrae, is there a temporary direct link you can provide in the meantime?

**Comment by ondrae** [comment]
Hi @donmccurdy @fureigh I've got this working again at http://civicissues.herokuapp.com/geeks/civicissues.

The code for america url should go back live sometime, but I wouldnt trust it again. Use the direct Heroku link for stability.

**Comment by donmccurdy** [comment]
Ok, thanks for the link (and good luck with the routing woes)!
