### ISSUE TITLE
Issue finder widget is returning wrong list of issues

### ISSUE THREAD

**Issue by schlos** [codeforamerica/civic-issue-finder#51]
If one group is selected and widget created at 
http://civicissues.codeforamerica.org/geeks/civicissues/embed

i.e. select "BetaNYC" (GH link: https://github.com/caciviclab)

brigade-information:
https://github.com/codeforamerica/brigade-information/blob/master/organizations.json#L62

Widget code:

`<iframe src="https://www.codeforamerica.org/geeks/civicissues/widget?organization_name=California-Civic-Lab&labels=help wanted&number=12" width="100%" height="600" frameBorder="0"></iframe>`

As a result iframe is returning wrong results (mixed with all other brigades, not only for repos under "caciviclab"):
[click a link and check](https://www.codeforamerica.org/geeks/civicissues/widget?organization_name=California-Civic-Lab&labels=help%20wanted&number=12)

**Comment by ondrae** [comment]
Woof. Sorry.

http://civicissues.codeforamerica.org/geeks/civicissues/widget?organization_name=California-Civic-Lab&labels=help+wanted&number=12 should work.

This tool got moved to a subdomain somehow, I don't know the full story there. It looks like https support got dropped too. I'll update the js that creates that embed link to reflect these changes.

Thanks for the ping.

**Comment by ondrae** [comment]
Closed by https://github.com/codeforamerica/civic-issue-finder/commit/3c6df5c8bab2c4a507f6d5f6a1a8214cfc574ea5

**Comment by ondrae** [comment]
Okay should be fixed. You may need to force reload to get the new javascript.
