### ISSUE TITLE
Loading and then disappearing

### ISSUE THREAD

**Issue by darthsaderr** [codeforamerica/civic-issue-finder#52]
At http://civicissues.codeforamerica.org/geeks/civicissues I can see the issues load in but after a second or so they disappear. There are several calls at the end of the page load with a status of 307 Internal Redirect to a google-analytics url (not sure if this is the culprit)

**Comment by lassiter** [comment]
same here, here is a screenshot https://www.dropbox.com/s/dufucs97v47n4g7/Screenshot%202017-09-28%2018.25.19.png?dl=0

**Comment by mdkarr01** [comment]
Having the same problem. Issues flash and then disappear. All ad blocking is disabled for the site. (Using Chrome on OSX)
